package smart

import "bytes"

// generatedSignatures are substrings that indicate a file was produced by a
// code generator. Matches are case-insensitive over the first few lines.
var generatedSignatures = [][]byte{
	[]byte("code generated"),
	[]byte("do not edit"),
	[]byte("@generated"),
	[]byte("autogenerated"),
	[]byte("auto-generated"),
	[]byte("automatically generated"),
	[]byte("this file was generated"),
}

// IsGeneratedHeader inspects the first 5 lines (bounded by 1KB) for generator
// comments.
func IsGeneratedHeader(content []byte) bool {
	if len(content) == 0 {
		return false
	}

	limit := 1024
	if len(content) < limit {
		limit = len(content)
	}
	header := content[:limit]

	lines := bytes.SplitN(header, []byte("\n"), 6)
	maxLines := len(lines)
	if maxLines > 5 {
		maxLines = 5
	}

	for i := 0; i < maxLines; i++ {
		line := bytes.ToLower(lines[i])
		for _, sig := range generatedSignatures {
			if bytes.Contains(line, sig) {
				return true
			}
		}
	}
	return false
}
