package smart

import "testing"

func TestSmartFilter(t *testing.T) {
	eval := New(15000)

	tests := []struct {
		name     string
		path     string
		content  []byte
		tokens   int
		wantSkip bool
	}{
		{name: "over token limit", path: "main.go", tokens: 16000, wantSkip: true},
		{name: "under token limit", path: "main.go", tokens: 5000, wantSkip: false},
		{name: "generated header", path: "code.go", content: []byte("// Code generated by tool. DO NOT EDIT.\npackage main"), tokens: 100, wantSkip: true},
		{name: "go.sum lock", path: "go.sum", tokens: 500, wantSkip: true},
		{name: "cargo lock", path: "Cargo.lock", tokens: 500, wantSkip: true},
		{name: "package lock", path: "package-lock.json", tokens: 500, wantSkip: true},
		{name: "minified js", path: "app.min.js", tokens: 500, wantSkip: true},
		{name: "protobuf go", path: "user.pb.go", tokens: 500, wantSkip: true},
		{name: "plain source", path: "main.go", content: []byte("package main\nfunc main() {}"), tokens: 10, wantSkip: false},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			skip, _ := eval.ShouldSkip(tc.path, tc.content, tc.tokens)
			if skip != tc.wantSkip {
				t.Errorf("ShouldSkip(%s) = %v, want %v", tc.path, skip, tc.wantSkip)
			}
		})
	}
}

func TestNewDefaultMaxTokens(t *testing.T) {
	e := New(0)
	if e.maxTokens != DefaultMaxTokens {
		t.Errorf("New(0).maxTokens = %d, want %d", e.maxTokens, DefaultMaxTokens)
	}
}

func TestReasonMessages(t *testing.T) {
	e := New(100)
	if skip, reason := e.ShouldSkip("main.go", nil, 200); !skip || reason == "" {
		t.Errorf("guardrail = (%v, %q), want (true, non-empty)", skip, reason)
	}

	if skip, reason := e.ShouldSkip("generated.pb.go", []byte("// DO NOT EDIT\n"), 10); !skip || reason != "Auto-generated file header detected" {
		t.Errorf("header = (%v, %q)", skip, reason)
	}

	if skip, reason := e.ShouldSkip("go.sum", nil, 10); !skip || reason != "Matched smart language filter" {
		t.Errorf("language rule = (%v, %q)", skip, reason)
	}
}
