package app

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/bethropolis/sift/internal/config"
)

// writeFile creates a file under root with the given content, creating parent
// directories as needed.
func writeFile(t *testing.T, root, rel, content string) {
	t.Helper()
	path := filepath.Join(root, filepath.FromSlash(rel))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func TestSmartFilterCollect(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "main.go", "package main\nfunc main() {}\n")
	writeFile(t, root, "user.pb.go", "package user\n")
	writeFile(t, root, "app.min.js", "var x=1;")
	writeFile(t, root, "package-lock.json", "{\"lockfileVersion\":3}")
	writeFile(t, root, "gen.go", "// Code generated by tool. DO NOT EDIT.\npackage gen\n")
	writeFile(t, root, "sub/Cargo.lock", "# cargo lock")

	collect := func(smartFilter bool) []string {
		cfg := config.New()
		cfg.RootDir = root
		cfg.Quiet = true
		cfg.OutputFile = "-"
		cfg.SmartFilter = smartFilter
		a, err := New(cfg)
		if err != nil {
			t.Fatal(err)
		}
		defer a.Close()
		files, _, err := a.Collect()
		if err != nil {
			t.Fatal(err)
		}
		paths := make([]string, 0, len(files))
		for _, f := range files {
			paths = append(paths, f.Path)
		}
		return paths
	}

	withoutSmart := collect(false)
	// package-lock.json is pruned by the built-in default ignore patterns
	// before smart filtering, so the baseline is the remaining five files.
	wantBaseline := []string{"app.min.js", "gen.go", "main.go", "sub/Cargo.lock", "user.pb.go"}
	if !sameSet(withoutSmart, wantBaseline) {
		t.Errorf("without smart: got %v, want %v", withoutSmart, wantBaseline)
	}

	withSmart := collect(true)
	if len(withSmart) != 1 || withSmart[0] != "main.go" {
		t.Errorf("with smart: got %v, want [main.go]", withSmart)
	}
}

func TestSmartFilterRecordsSkipped(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "main.go", "package main\n")
	writeFile(t, root, "go.sum", "hash line\n")

	cfg := config.New()
	cfg.RootDir = root
	cfg.Quiet = true
	cfg.OutputFile = "-"
	cfg.SmartFilter = true
	a, err := New(cfg)
	if err != nil {
		t.Fatal(err)
	}
	defer a.Close()

	files, skipped, err := a.Collect()
	if err != nil {
		t.Fatal(err)
	}
	if len(files) != 1 {
		t.Errorf("files = %d, want 1", len(files))
	}
	var found bool
	for _, s := range skipped {
		if s.Path == "go.sum" {
			found = true
			if s.Reason != "Skipped (Smart Filter)" {
				t.Errorf("reason = %q", s.Reason)
			}
		}
	}
	if !found {
		t.Errorf("go.sum not recorded in skipped items: %+v", skipped)
	}
}

func TestSmartFilterMaxTokens(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "big.go", "package big\n")

	cfg := config.New()
	cfg.RootDir = root
	cfg.Quiet = true
	cfg.OutputFile = "-"
	cfg.SmartFilter = true
	cfg.SmartMaxTokens = 1
	a, err := New(cfg)
	if err != nil {
		t.Fatal(err)
	}
	defer a.Close()

	files, _, err := a.Collect()
	if err != nil {
		t.Fatal(err)
	}
	if len(files) != 0 {
		t.Errorf("files = %d, want 0 (big.go exceeds 1-token ceiling)", len(files))
	}
}

// sameSet reports whether got and want contain the same paths, regardless of
// order.
func sameSet(got, want []string) bool {
	if len(got) != len(want) {
		return false
	}
	wantSet := make(map[string]bool, len(want))
	for _, w := range want {
		wantSet[w] = true
	}
	for _, g := range got {
		if !wantSet[g] {
			return false
		}
	}
	return true
}
