// Package desktop installs and removes OS launcher entries that open
// `sift serve --app`: an XDG .desktop file on Linux and a Sift.app bundle on
// macOS. Other platforms report an unsupported error.
//
// Everything is user-local (no root, no system dirs) and marked, so uninstall
// only ever removes files this package created: an unmarked file at one of
// these paths is left alone with an explanatory error. Install is idempotent
// and also repairs a stale entry (e.g. after the binary moved).
//
// The icon (icon.png, embedded) is rendered from icon.svg, which copies the
// mark geometry from web/src/lib/favicon.ts. Re-render at 512x512 if the mark
// ever changes.
package desktop

import (
	_ "embed"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
)

//go:embed icon.png
var iconPNG []byte

// marker owns a file: the first line (or an XML comment) of everything
// install writes. Uninstall refuses files without it.
const marker = "generated by sift desktop install"

// Report describes one install/uninstall/status outcome for the CLI to print.
type Report struct {
	// Files created or removed.
	Files []string
	// Icon is false when the entry installed without its icon (macOS
	// without sips): usable, just iconless.
	Icon bool
}

// ErrUnsupported means the OS has no launcher support in this package.
var ErrUnsupported = errors.New("desktop launchers are supported on Linux and macOS")

// ErrForeign means a file already exists at an install path but was not
// created by this package; it is left alone.
type ErrForeign struct{ Path string }

func (e *ErrForeign) Error() string {
	return fmt.Sprintf("%s was not created by sift (no install marker); leaving it alone", e.Path)
}

// exe resolves the running binary for the launcher's Exec line.
func exe() (string, error) {
	p, err := os.Executable()
	if err != nil {
		return "", fmt.Errorf("locate sift binary: %w", err)
	}
	abs, err := filepath.Abs(p)
	if err != nil {
		return "", fmt.Errorf("locate sift binary: %w", err)
	}
	return abs, nil
}

// Install creates the launcher for this OS. Re-running repairs it.
func Install(version string) (Report, error) {
	switch runtime.GOOS {
	case "linux":
		return installLinux()
	case "darwin":
		return installDarwin(version)
	default:
		return Report{}, ErrUnsupported
	}
}

// Uninstall removes the launcher for this OS. Missing files are success.
func Uninstall() (Report, error) {
	switch runtime.GOOS {
	case "linux":
		return uninstallLinux()
	case "darwin":
		return uninstallDarwin()
	default:
		return Report{}, ErrUnsupported
	}
}

// Status reports whether a launcher installed by this package exists.
func Status() (Report, error) {
	switch runtime.GOOS {
	case "linux":
		return statusLinux(), nil
	case "darwin":
		return statusDarwin(), nil
	default:
		return Report{}, ErrUnsupported
	}
}

// owned reports whether path exists and carries the marker.
func owned(path string) bool {
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	return strings.Contains(string(data), marker)
}

// writeFile creates parents and writes a private-then-shared file. Entries
// carry no secrets, so 0644; the macOS launcher script is chmodded +x after.
func writeFile(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, data, 0o644)
}
