// Package web embeds the built Svelte single-page app served by `sift serve`.
//
// web/dist holds exactly one committed dotfile (.keep); the built assets are
// generated by `just web` and force-added only on release tag commits, so
// `go install ...@vX.Y.Z` ships the UI while main stays clean.
package web

import "embed"

// DistFS holds the precompressed web UI. Every file is stored as file.gz;
// the server sets Content-Encoding: gzip and only decompresses for clients
// that do not accept gzip.
//
//go:embed all:dist
var DistFS embed.FS
